### PR TITLE
Use String type for Puppet 4

### PR DESCRIPTION
**Pull request by hfm**
@lamanotrama Hi. This module doest'n work in Puppet 4.

### CODE REVIEW

**Comment by lamanotrama** [comment]
Oh! Puppet4…
Thank you for the patch 😃

**Comment by lamanotrama** [comment]
@hfm 
BTW, I would like to transfer this project to your account. How do you think?

**Comment by hfm** [comment]
YES!
I'll maintain this module 👍

**Comment by lamanotrama** [comment]
Thanks.
I sent the request. Please accept it.

**Comment by hfm** [comment]
Done!

**Pull request merged**
